// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_UnlockScreen
void ui_UnlockScreen_screen_init(void);
lv_obj_t *ui_UnlockScreen;
lv_obj_t *ui_Keyboard;
void ui_event_TextArea(lv_event_t *e);
lv_obj_t *ui_TextArea;

// SCREEN: ui_LockScreen
void ui_LockScreen_screen_init(void);
lv_obj_t *ui_LockScreen;
void ui_event_ArmHomeButton(lv_event_t *e);
lv_obj_t *ui_ArmHomeButton;
void ui_event_ArmNightButton(lv_event_t *e);
lv_obj_t *ui_ArmNightButton;
void ui_event_ArmAwayButton(lv_event_t *e);
lv_obj_t *ui_ArmAwayButton;
lv_obj_t *ui_ArmAwayLabel;
lv_obj_t *ui_ArmNightLabel;
void ui_event_ArmHomeLabel(lv_event_t *e);
lv_obj_t *ui_ArmHomeLabel;
lv_obj_t *ui_StatusLabel;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP != 0
#error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_TextArea(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_keyboard_set_target(ui_Keyboard, ui_TextArea);
    }
    if (event_code == LV_EVENT_READY)
    {
        ProcessPin(e);
    }
}
void ui_event_ArmHomeButton(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        arm_home(e);
        _ui_label_set_property(ui_StatusLabel, _UI_LABEL_PROPERTY_TEXT, "Arming Home");
    }
}
void ui_event_ArmNightButton(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        arm_night(e);
        _ui_label_set_property(ui_StatusLabel, _UI_LABEL_PROPERTY_TEXT, "Arming Night");
    }
}
void ui_event_ArmAwayButton(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        arm_away(e);
        _ui_label_set_property(ui_StatusLabel, _UI_LABEL_PROPERTY_TEXT, "Arming Away");
    }
}
void ui_event_ArmHomeLabel(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        arm_home(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t *dispp = lv_disp_get_default();
    lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_UnlockScreen_screen_init();
    ui_LockScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_UnlockScreen);
}
