// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C"
{
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
  // SCREEN: ui_UnlockScreen
  void ui_UnlockScreen_screen_init(void);
  extern lv_obj_t *ui_UnlockScreen;
  extern lv_obj_t *ui_Keyboard;
  void ui_event_TextArea(lv_event_t *e);
  extern lv_obj_t *ui_TextArea;
  // SCREEN: ui_LockScreen
  void ui_LockScreen_screen_init(void);
  extern lv_obj_t *ui_LockScreen;
  void ui_event_ArmHomeButton(lv_event_t *e);
  extern lv_obj_t *ui_ArmHomeButton;
  void ui_event_ArmNightButton(lv_event_t *e);
  extern lv_obj_t *ui_ArmNightButton;
  void ui_event_ArmAwayButton(lv_event_t *e);
  extern lv_obj_t *ui_ArmAwayButton;
  extern lv_obj_t *ui_ArmAwayLabel;
  extern lv_obj_t *ui_ArmNightLabel;
  void ui_event_ArmHomeLabel(lv_event_t *e);
  extern lv_obj_t *ui_ArmHomeLabel;
  extern lv_obj_t *ui_StatusLabel;
  extern lv_obj_t *ui____initial_actions0;

  void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
