// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

/*void ProcessPin(lv_event_t *e)
{
	// Your code here
}

void arm_home(lv_event_t *e)
{
	// Your code here
}

void arm_night(lv_event_t *e)
{
	// Your code here
}

void arm_away(lv_event_t *e)
{
	// Your code here
}*/
